#!/usr/bin/env bash

## set this to your active development branch
# develop_branch="develop"
# current_branch="$(git rev-parse --abbrev-ref HEAD)"
#
## only check commit messages on main development branch
#[ "$current_branch" != "$develop_branch" ] && exit 0

# regex to validate in commit msg
commit_regex='\[#[0-9]+\](\[[a-zA-Z& ]+\])*:.*'
error_msg="Commit aborted. Please write the commit message in correct format, e.g., [#51][Jason & Jane]: Commit Message."

# Compatible with IntelliJ IDEA Git Hooks check.
if [ -f "$1" ]; then
  value=$(cat "$1")
  commit_msg=$(echo "${value}" | grep -Eo "${commit_regex}")
else
  # Common Git Hooks check
  commit_msg=$(echo "$1" | grep -Eo "${commit_regex}")
fi

if [ -z "${commit_msg}" ]; then
  echo "$error_msg" >&2
  exit 1
fi
